---
site_name: TRaSH Guides
site_description: Guides mainly for Sonarr/Radarr/Bazarr and everything related to it.
site_author: TRaSH
site_url: https://trash-guides.info/

repo_url: https://github.com/TRaSH-/Guides
repo_name: TRaSH-/Guides

copyright: Copyright &copy; 2020 TRaSH

extra:
  manifest: manifest.webmanifest

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "[["
      j2_variable_end_string: "]]"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  language: en
  palette:
    primary: indigo
    accent: red
    scheme: slate
  font:
    code: "Fira Code"
  favicon: img/favicon.png
