site_name: TRaSH Guides
site_description: Guides mainly for Sonarr/Radarr/Bazarr and everything related to it.
site_author: TRaSH
site_url: https://trash-guides.info/

repo_url: https://github.com/TRaSH-/Guides
repo_name: TRaSH-/Guides

copyright: Copyright &copy; 2022 TRaSH

extra:
  analytics:
    provider: google
    property: G-ZZKM4MPQXL
  social:
    - icon: fontawesome/brands/discord
      link: https://trash-guides.info/discord
    - icon: fontawesome/brands/github-square
      link: https://github.com/TRaSH-/Guides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tilde
  - lightgallery
  - codehilite:
      guess_lang: true
  - toc:
      permalink: "Â¶"
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - include-markdown:
  - search
  - git-revision-date-localized:
      type: datetime
      locale: en
  #    fallback_to_build_date: false
  - awesome-pages
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "[["
      j2_variable_end_string: "]]"
  - redirects:
      redirect_maps:
        updates.txt: updates.txt
        discord.md: https://discord.gg/Vau8dZ3
        syno-script.md: https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/script/trash_syno_installer.sh
        # Radarr old redirects
        Radarr/V3/How-to-importexport-Custom-Formats-and-truly-make-use-of-it.md: Radarr/Radarr-import-custom-formats.md
        Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md: Radarr/Radarr-collection-of-custom-formats.md
        Radarr/V3/Radarr-collection-of-custom-formats.md: Radarr/Radarr-collection-of-custom-formats.md
        Radarr/V3/Radarr-import-custom-formats.md: Radarr/Radarr-import-custom-formats.md
        Radarr/V3/Radarr-Quality-Settings-File-Size.md: Radarr/Radarr-Quality-Settings-File-Size.md
        Radarr/V3/Radarr-recommended-naming-scheme.md: Radarr/Radarr-recommended-naming-scheme.md
        Radarr/V3/Radarr-remote-path-mapping.md: Radarr/Radarr-remote-path-mapping.md
        Radarr/V3/Radarr-setup-custom-formats.md: Radarr/Radarr-setup-custom-formats.md
        Radarr/V3/Tips/Radarr-add-a-movie-collection.md: Radarr/Tips/Radarr-add-a-movie-collection.md
        Radarr/V3/Tips/Radarr-rename-your-folders.md: Radarr/Tips/Radarr-rename-your-folders.md
        Radarr/V3/Tips/Radarr-show-unknown-movie-items.md: Radarr/Tips/Radarr-show-unknown-movie-items.md
        # Sonarr old redirects
        Sonarr/V3/Remote-Path-Mappings-explained-for-Sonarr.md: Sonarr/Sonarr-remote-path-mapping.md
        Sonarr/V3/Sonarr-Quality-Settings-File-Size.md: Sonarr/Sonarr-Quality-Settings-File-Size.md
        Sonarr/V3/Sonarr-recommended-naming-scheme.md: Sonarr/Sonarr-recommended-naming-scheme.md
        Sonarr/V3/Sonarr-Release-Profile-RegEx.md: Sonarr/Sonarr-Release-Profile-RegEx.md
        Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md: Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
        Sonarr/V3/Sonarr-remote-path-mapping.md: Sonarr/Sonarr-remote-path-mapping.md
        # Downloader old redirects
        NZBGet/How-to-setup-NZBGet.md: Downloaders/NZBGet/Basic-Setup.md
        NZBGet/scripts/index.md: Downloaders/NZBGet/scripts/index.md
        # Hardlinks old redirects
        Misc/how-to-set-up-hardlinks-and-atomic-moves.md: Hardlinks/Hardlinks-and-Instant-Moves.md
        # Shortcuts redirects
        hardlinks.md: Hardlinks/Hardlinks-and-Instant-Moves.md
        hardlink.md: Hardlinks/Hardlinks-and-Instant-Moves.md
        check-hardlinks.md: Hardlinks/Check-if-hardlinks-are-working.md
        custom-formats.md: Radarr/Radarr-collection-of-custom-formats.md
        cf.md: Radarr/Radarr-collection-of-custom-formats.md
        TorGuard.md: Misc/How-to-setup-Torguard-for-port-forwarding.md
        torguard.md: Misc/How-to-setup-Torguard-for-port-forwarding.md
        compose.md: Misc/how-to-provide-a-docker-compose.md
        Golden-Rule.md: Misc/x265-4k.md
        show-unknown.md: Radarr/Tips/Radarr-show-unknown-movie-items.md
        merge-quality.md: Radarr/Tips/Merge-quality.md
        jdupes.md: Hardlinks/Replace-copies-with-hardlinks.md
        How-to-setup-for/index.md: Hardlinks/How-to-setup-for/index.md
        How-to-setup-for/Docker.md: Hardlinks/How-to-setup-for/Docker.md
        How-to-setup-for/Dockstarter.md: Hardlinks/How-to-setup-for/Dockstarter.md
        How-to-setup-for/Native.md: Hardlinks/How-to-setup-for/Native.md
        How-to-setup-for/Synology.md: Hardlinks/How-to-setup-for/Synology.md
        How-to-setup-for/Unraid.md: Hardlinks/How-to-setup-for/Unraid.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: indigio
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"
  favicon: img/favicon.png
  logo: img/logo.png
