name: Validate Custom Format JSONs

on:
  push:
    paths:
      - .github/workflows/custom-format-validation.yml
      - docs/json/guide-only/*.json
      - docs/json/radarr/cf/*.json
      - docs/json/sonarr/cf/*.json
      - schemas/**/*.json
  pull_request:
    paths:
      - .github/workflows/custom-format-validation.yml
      - docs/json/guide-only/*.json
      - docs/json/radarr/cf/*.json
      - docs/json/sonarr/cf/*.json
      - schemas/**/*.json

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Validate Guide only Custom Formats
        run: check-jsonschema -v --schemafile schemas/guide-only-cf.schema.json docs/json/guide-only/*.json

      - name: Validate Radarr Custom Formats
        run: check-jsonschema -v --schemafile schemas/radarr-cf.schema.json docs/json/radarr/cf/*.json

      - name: Validate Sonarr Custom Formats
        run: check-jsonschema -v --schemafile schemas/sonarr-cf.schema.json docs/json/sonarr/cf/*.json
