name: Lint - YAML

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Run yamllint
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/yaml \
            peterdavehello/yamllint \
            yamllint \
            -c "/yaml/yamllint.yml" \
            .
