name: Lint

on: [push, pull_request]

jobs:

  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: editorconfig-checker
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/check \
            mstruebing/editorconfig-checker

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: markdownlint
        run: |
          find "${GITHUB_WORKSPACE}" -name '*.md' -exec \
            docker run --rm \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" \
            markdownlint/markdownlint \
            -r ~MD013,~MD033,~MD034,~MD046,~MD002,~MD041 \
            {} +

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: yamllint
        run: |
          find "${GITHUB_WORKSPACE}" -name '*.yaml' -o -name '*.yml' -exec \
            docker run --rm \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" \
            peterdavehello/yamllint \
            yamllint -d '{"extends":"default","rules":{"document-start":{"present":false},"line-length":"disable","truthy":{"check-keys":false}}}' \
            {} +
